#the NodePort service will create based on the pods where the lables of the pods have the below
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: webserver
    tier: frontend
